/**
 * List of active F&O stocks provided by user.
 * This universe is used for 1-minute real-time scanners (Options Opportunities, Intraday Breakouts, etc.)
 * rather than scanning the entire 1,600+ NSE EQ universe every minute.
 */
const FO_UNIVERSE = [
  { symbol: "AARTIIND", name: "Aarti Industries" },
  { symbol: "ABB", name: "ABB India" },
  { symbol: "ABCAPITAL", name: "Aditya Birla Capital" },
  { symbol: "ACC", name: "ACC" },
  { symbol: "ADANIENT", name: "Adani Enterprises" },
  { symbol: "ADANIGREEN", name: "Adani Green Energy" },
  { symbol: "ADANIPORTS", name: "Adani Ports" },
  { symbol: "ADANIPOWER", name: "Adani Power" },
  { symbol: "AMBUJACEM", name: "Ambuja Cements" },
  { symbol: "ANGELONE", name: "Angel One" },
  { symbol: "APOLLOHOSP", name: "Apollo Hospitals" },
  { symbol: "APOLLOTYRE", name: "Apollo Tyres" },
  { symbol: "ASHOKLEY", name: "Ashok Leyland" },
  { symbol: "ASIANPAINT", name: "Asian Paints" },
  { symbol: "ASTRAL", name: "Astral" },
  { symbol: "ATGL", name: "Adani Total Gas" },
  { symbol: "AUBANK", name: "AU Small Finance Bank" },
  { symbol: "AUROPHARMA", name: "Aurobindo Pharma" },
  { symbol: "AXISBANK", name: "Axis Bank" },
  { symbol: "BAJAJ-AUTO", name: "Bajaj Auto" },
  { symbol: "BAJAJFINSV", name: "Bajaj Finserv" },
  { symbol: "BAJFINANCE", name: "Bajaj Finance" },
  { symbol: "BAJAJHLDNG", name: "Bajaj Holdings" },
  { symbol: "BALKRISIND", name: "Balkrishna Industries" },
  { symbol: "BANDHANBNK", name: "Bandhan Bank" },
  { symbol: "BANKBARODA", name: "Bank of Baroda" },
  { symbol: "BATAINDIA", name: "Bata India" },
  { symbol: "BEL", name: "Bharat Electronics" },
  { symbol: "BHARATFORG", name: "Bharat Forge" },
  { symbol: "BHARTIARTL", name: "Bharti Airtel" },
  { symbol: "BHEL", name: "Bharat Heavy Electricals" },
  { symbol: "BIOCON", name: "Biocon" },
  { symbol: "BOSCHLTD", name: "Bosch" },
  { symbol: "BPCL", name: "Bharat Petroleum" },
  { symbol: "BRITANNIA", name: "Britannia" },
  { symbol: "BSE", name: "BSE Ltd" },
  { symbol: "BSOFT", name: "Birlasoft" },
  { symbol: "CANBK", name: "Canara Bank" },
  { symbol: "CANFINHOME", name: "Can Fin Homes" },
  { symbol: "CDSL", name: "CDSL" },
  { symbol: "CHAMBLFERT", name: "Chambal Fertilisers" },
  { symbol: "CIPLA", name: "Cipla" },
  { symbol: "COALINDIA", name: "Coal India" },
  { symbol: "COCHINSHIP", name: "Cochin Shipyard" },
  { symbol: "COFORGE", name: "Coforge" },
  { symbol: "COLPAL", name: "Colgate Palmolive" },
  { symbol: "CONCOR", name: "Container Corporation" },
  { symbol: "COROMANDEL", name: "Coromandel International" },
  { symbol: "CROMPTON", name: "Crompton Greaves" },
  { symbol: "CUMMINSIND", name: "Cummins India" },
  { symbol: "CYIENT", name: "Cyient" },
  { symbol: "DABUR", name: "Dabur" },
  { symbol: "DALBHARAT", name: "Dalmia Bharat" },
  { symbol: "DELHIVERY", name: "Delhivery" },
  { symbol: "DIVISLAB", name: "Divi's Laboratories" },
  { symbol: "DIXON", name: "Dixon Technologies" },
  { symbol: "DLF", name: "DLF" },
  { symbol: "DRREDDY", name: "Dr Reddy's" },
  { symbol: "EICHERMOT", name: "Eicher Motors" },
  { symbol: "ESCORTS", name: "Escorts Kubota" },
  { symbol: "EXIDEIND", name: "Exide Industries" },
  { symbol: "FEDERALBNK", name: "Federal Bank" },
  { symbol: "FORCEMOT", name: "Force Motors" },
  { symbol: "GAIL", name: "GAIL" },
  { symbol: "GLENMARK", name: "Glenmark" },
  { symbol: "GODFRYPHLP", name: "Godfrey Phillips" },
  { symbol: "GODREJCP", name: "Godrej Consumer" },
  { symbol: "GODREJPROP", name: "Godrej Properties" },
  { symbol: "GRANULES", name: "Granules India" },
  { symbol: "GRASIM", name: "Grasim" },
  { symbol: "HAL", name: "Hindustan Aeronautics" },
  { symbol: "HAVELLS", name: "Havells" },
  { symbol: "HCLTECH", name: "HCL Technologies" },
  { symbol: "HDFCAMC", name: "HDFC AMC" },
  { symbol: "HDFCBANK", name: "HDFC Bank" },
  { symbol: "HDFCLIFE", name: "HDFC Life" },
  { symbol: "HEROMOTOCO", name: "Hero MotoCorp" },
  { symbol: "HINDALCO", name: "Hindalco" },
  { symbol: "HINDCOPPER", name: "Hindustan Copper" },
  { symbol: "HINDPETRO", name: "HPCL" },
  { symbol: "HINDUNILVR", name: "Hindustan Unilever" },
  { symbol: "HUDCO", name: "HUDCO" },
  { symbol: "HYUNDAI", name: "Hyundai Motor India" },
  { symbol: "ICICIBANK", name: "ICICI Bank" },
  { symbol: "ICICIGI", name: "ICICI Lombard" },
  { symbol: "ICICIPRULI", name: "ICICI Prudential" },
  { symbol: "IDEX", name: "Ideaforge" },
  { symbol: "IDFCFIRSTB", name: "IDFC First Bank" },
  { symbol: "IEX", name: "Indian Energy Exchange" },
  { symbol: "IGL", name: "Indraprastha Gas" },
  { symbol: "INDHOTEL", name: "Indian Hotels" },
  { symbol: "INDIAMART", name: "IndiaMART" },
  { symbol: "INDIGO", name: "InterGlobe Aviation" },
  { symbol: "INDUSINDBK", name: "IndusInd Bank" },
  { symbol: "INDUSTOWER", name: "Indus Towers" },
  { symbol: "INFY", name: "Infosys" },
  { symbol: "IOC", name: "Indian Oil" },
  { symbol: "IRB", name: "IRB Infrastructure" },
  { symbol: "IRCTC", name: "IRCTC" },
  { symbol: "IREDA", name: "IREDA" },
  { symbol: "IRFC", name: "IRFC" },
  { symbol: "ITC", name: "ITC" },
  { symbol: "JINDALSTEL", name: "Jindal Steel" },
  { symbol: "JIOFIN", name: "Jio Financial Services" },
  { symbol: "JKCEMENT", name: "JK Cement" },
  { symbol: "JSWENERGY", name: "JSW Energy" },
  { symbol: "JSWSTEEL", name: "JSW Steel" },
  { symbol: "JUBLFOOD", name: "Jubilant FoodWorks" },
  { symbol: "KALYANKJIL", name: "Kalyan Jewellers" },
  { symbol: "KOTAKBANK", name: "Kotak Mahindra Bank" },
  { symbol: "LALPATHLAB", name: "Dr Lal PathLabs" },
  { symbol: "LAURUSLABS", name: "Laurus Labs" },
  { symbol: "LICHSGFIN", name: "LIC Housing Finance" },
  { symbol: "LICI", name: "LIC" },
  { symbol: "LODHA", name: "Macrotech Developers" },
  { symbol: "LT", name: "Larsen & Toubro" },
  { symbol: "LTF", name: "L&T Finance" },
  { symbol: "LTIM", name: "LTIMindtree" },
  { symbol: "LTTS", name: "L&T Technology Services" },
  { symbol: "LUPIN", name: "Lupin" },
  { symbol: "M&M", name: "Mahindra & Mahindra" },
  { symbol: "M&MFIN", name: "Mahindra Finance" },
  { symbol: "MANAPPURAM", name: "Manappuram Finance" },
  { symbol: "MARICO", name: "Marico" },
  { symbol: "MARUTI", name: "Maruti Suzuki" },
  { symbol: "MAXHEALTH", name: "Max Healthcare" },
  { symbol: "MAZDOCK", name: "Mazagon Dock" },
  { symbol: "MCX", name: "Multi Commodity Exchange" },
  { symbol: "METROPOLIS", name: "Metropolis" },
  { symbol: "MFSL", name: "Max Financial Services" },
  { symbol: "MGL", name: "Mahanagar Gas" },
  { symbol: "MOTHERSON", name: "Samvardhana Motherson" },
  { symbol: "MOTILALOFS", name: "Motilal Oswal Financial" },
  { symbol: "MPHASIS", name: "Mphasis" },
  { symbol: "MRF", name: "MRF" },
  { symbol: "MUTHOOTFIN", name: "Muthoot Finance" },
  { symbol: "NAM-INDIA", name: "Nippon Life India AMC" },
  { symbol: "NAUKRI", name: "Info Edge" },
  { symbol: "NAVINFLUOR", name: "Navin Fluorine" },
  { symbol: "NESTLEIND", name: "Nestle India" },
  { symbol: "NHPC", name: "NHPC" },
  { symbol: "NMDC", name: "NMDC" },
  { symbol: "NTPC", name: "NTPC" },
  { symbol: "NYKAA", name: "FSN E-Commerce" },
  { symbol: "OBEROIRLTY", name: "Oberoi Realty" },
  { symbol: "OFSS", name: "Oracle Financial Services" },
  { symbol: "OIL", name: "Oil India" },
  { symbol: "ONGC", name: "ONGC" },
  { symbol: "PAGEIND", name: "Page Industries" },
  { symbol: "PATANJALI", name: "Patanjali Foods" },
  { symbol: "PEL", name: "Piramal Enterprises" },
  { symbol: "PERSISTENT", name: "Persistent Systems" },
  { symbol: "PETRONET", name: "Petronet LNG" },
  { symbol: "PFC", name: "Power Finance" },
  { symbol: "PIDILITIND", name: "Pidilite" },
  { symbol: "PIIND", name: "PI Industries" },
  { symbol: "PNB", name: "Punjab National Bank" },
  { symbol: "POLYCAB", name: "Polycab" },
  { symbol: "POWERGRID", name: "Power Grid" },
  { symbol: "POWERINDIA", name: "Hitachi Energy India" },
  { symbol: "PREMIERENE", name: "Premier Energies" },
  { symbol: "PRESTIGE", name: "Prestige Estates" },
  { symbol: "RECLTD", name: "REC" },
  { symbol: "RELIANCE", name: "Reliance Industries" },
  { symbol: "SAIL", name: "SAIL" },
  { symbol: "SAMMAANCAP", name: "Sammaan Capital" },
  { symbol: "SBICARD", name: "SBI Cards" },
  { symbol: "SBILIFE", name: "SBI Life" },
  { symbol: "SBIN", name: "State Bank of India" },
  { symbol: "SHREECEM", name: "Shree Cement" },
  { symbol: "SHRIRAMFIN", name: "Shriram Finance" },
  { symbol: "SIEMENS", name: "Siemens" },
  { symbol: "SOLARINDS", name: "Solar Industries" },
  { symbol: "SONACOMS", name: "Sona BLW" },
  { symbol: "SRF", name: "SRF" },
  { symbol: "SUNPHARMA", name: "Sun Pharma" },
  { symbol: "SUNTV", name: "Sun TV" },
  { symbol: "SUPREMEIND", name: "Supreme Industries" },
  { symbol: "SWIGGY", name: "Swiggy" },
  { symbol: "SYNGENE", name: "Syngene" },
  { symbol: "TATACHEM", name: "Tata Chemicals" },
  { symbol: "TATACOMM", name: "Tata Communications" },
  { symbol: "TATACONSUM", name: "Tata Consumer" },
  { symbol: "TATAMOTORS", name: "Tata Motors" },
  { symbol: "TATAPOWER", name: "Tata Power" },
  { symbol: "TATASTEEL", name: "Tata Steel" },
  { symbol: "TCS", name: "Tata Consultancy Services" },
  { symbol: "TECHM", name: "Tech Mahindra" },
  { symbol: "TITAN", name: "Titan" },
  { symbol: "TORNTPHARM", name: "Torrent Pharma" },
  { symbol: "TORNTPOWER", name: "Torrent Power" },
  { symbol: "TRENT", name: "Trent" },
  { symbol: "TVSMOTOR", name: "TVS Motor" },
  { symbol: "ULTRACEMCO", name: "UltraTech Cement" },
  { symbol: "UNIONBANK", name: "Union Bank" },
  { symbol: "UNITEDSPIRITS", name: "United Spirits" },
  { symbol: "UPL", name: "UPL" },
  { symbol: "VBL", name: "Varun Beverages" },
  { symbol: "VEDL", name: "Vedanta" },
  { symbol: "VMM", name: "Vishal Mega Mart" },
  { symbol: "VOLTAS", name: "Voltas" },
  { symbol: "WAAREEENER", name: "Waaree Energies" },
  { symbol: "WIPRO", name: "Wipro" },
  { symbol: "YESBANK", name: "Yes Bank" },
  { symbol: "ZOMATO", name: "Eternal (formerly Zomato)" },
  { symbol: "ZYDUSLIFE", name: "Zydus Life" }
];

module.exports = FO_UNIVERSE;
