/**
 * Active F&O universe — used for intraday scanners, live subscriptions, and historical regen.
 * Each entry includes sector for cockpit filtering and sector-strength widgets.
 */
const FO_UNIVERSE = [
  { symbol: "AARTIIND", name: "Aarti Industries", sector: "Chemicals" },
  { symbol: "ABB", name: "ABB India", sector: "Capital Goods" },
  { symbol: "ABCAPITAL", name: "Aditya Birla Capital", sector: "Financial Services" },
  { symbol: "ABFRL", name: "Aditya Birla Fashion", sector: "Consumer Services" },
  { symbol: "ACC", name: "ACC", sector: "Construction Materials" },
  { symbol: "ADANIENT", name: "Adani Enterprises", sector: "Metals & Mining" },
  { symbol: "ADANIENSOL", name: "Adani Energy Solutions", sector: "Power" },
  { symbol: "ADANIGREEN", name: "Adani Green Energy", sector: "Power" },
  { symbol: "ADANIPORTS", name: "Adani Ports", sector: "Services" },
  { symbol: "ADANIPOWER", name: "Adani Power", sector: "Power" },
  { symbol: "ALKEM", name: "Alkem Laboratories", sector: "Healthcare" },
  { symbol: "AMBUJACEM", name: "Ambuja Cements", sector: "Construction Materials" },
  { symbol: "ANGELONE", name: "Angel One", sector: "Financial Services" },
  { symbol: "APLAPOLLO", name: "APL Apollo Tubes", sector: "Capital Goods" },
  { symbol: "APOLLOHOSP", name: "Apollo Hospitals", sector: "Healthcare" },
  { symbol: "APOLLOTYRE", name: "Apollo Tyres", sector: "Automobile and Auto Components" },
  { symbol: "ASHOKLEY", name: "Ashok Leyland", sector: "Automobile and Auto Components" },
  { symbol: "ASIANPAINT", name: "Asian Paints", sector: "Consumer Durables" },
  { symbol: "ASTRAL", name: "Astral", sector: "Capital Goods" },
  { symbol: "AUBANK", name: "AU Small Finance Bank", sector: "Financial Services" },
  { symbol: "AUROPHARMA", name: "Aurobindo Pharma", sector: "Healthcare" },
  { symbol: "AXISBANK", name: "Axis Bank", sector: "Financial Services" },
  { symbol: "BAJAJ-AUTO", name: "Bajaj Auto", sector: "Automobile and Auto Components" },
  { symbol: "BAJAJFINSV", name: "Bajaj Finserv", sector: "Financial Services" },
  { symbol: "BAJAJHLDNG", name: "Bajaj Holdings", sector: "Financial Services" },
  { symbol: "BAJFINANCE", name: "Bajaj Finance", sector: "Financial Services" },
  { symbol: "BALKRISIND", name: "Balkrishna Industries", sector: "Automobile and Auto Components" },
  { symbol: "BANDHANBNK", name: "Bandhan Bank", sector: "Financial Services" },
  { symbol: "BANKBARODA", name: "Bank of Baroda", sector: "Financial Services" },
  { symbol: "BANKBOI", name: "Bank of India", sector: "Financial Services" },
  { symbol: "BEL", name: "Bharat Electronics", sector: "Capital Goods" },
  { symbol: "BHARATFORG", name: "Bharat Forge", sector: "Automobile and Auto Components" },
  { symbol: "BHARTIARTL", name: "Bharti Airtel", sector: "Telecommunication" },
  { symbol: "BHEL", name: "Bharat Heavy Electricals", sector: "Capital Goods" },
  { symbol: "BIOCON", name: "Biocon", sector: "Healthcare" },
  { symbol: "BOSCHLTD", name: "Bosch", sector: "Automobile and Auto Components" },
  { symbol: "BPCL", name: "Bharat Petroleum", sector: "Oil, Gas & Consumable Fuels" },
  { symbol: "BSE", name: "BSE Ltd", sector: "Financial Services" },
  { symbol: "BSOFT", name: "Birlasoft", sector: "Information Technology" },
  { symbol: "CAMS", name: "Computer Age Management Services", sector: "Financial Services" },
  { symbol: "CANBK", name: "Canara Bank", sector: "Financial Services" },
  { symbol: "CANFINHOME", name: "Can Fin Homes", sector: "Financial Services" },
  { symbol: "CDSL", name: "CDSL", sector: "Financial Services" },
  { symbol: "CGPOWER", name: "CG Power", sector: "Capital Goods" },
  { symbol: "CHAMBLFERT", name: "Chambal Fertilisers", sector: "Chemicals" },
  { symbol: "CHOLAFIN", name: "Cholamandalam Investment", sector: "Financial Services" },
  { symbol: "CIPLA", name: "Cipla", sector: "Healthcare" },
  { symbol: "COALINDIA", name: "Coal India", sector: "Oil, Gas & Consumable Fuels" },
  { symbol: "COCHINSHIP", name: "Cochin Shipyard", sector: "Capital Goods" },
  { symbol: "COFORGE", name: "Coforge", sector: "Information Technology" },
  { symbol: "COLPAL", name: "Colgate Palmolive", sector: "FMCG" },
  { symbol: "CONCOR", name: "Container Corporation", sector: "Services" },
  { symbol: "CROMPTON", name: "Crompton Greaves", sector: "Consumer Durables" },
  { symbol: "CUMMINSIND", name: "Cummins India", sector: "Capital Goods" },
  { symbol: "CYIENT", name: "Cyient", sector: "Information Technology" },
  { symbol: "DABUR", name: "Dabur", sector: "FMCG" },
  { symbol: "DALBHARAT", name: "Dalmia Bharat", sector: "Construction Materials" },
  { symbol: "DEEPAKNTR", name: "Deepak Nitrite", sector: "Chemicals" },
  { symbol: "DELHIVERY", name: "Delhivery", sector: "Services" },
  { symbol: "DIVISLAB", name: "Divi's Laboratories", sector: "Healthcare" },
  { symbol: "DIXON", name: "Dixon Technologies", sector: "Consumer Durables" },
  { symbol: "DLF", name: "DLF", sector: "Realty" },
  { symbol: "DRREDDY", name: "Dr Reddy's", sector: "Healthcare" },
  { symbol: "EICHERMOT", name: "Eicher Motors", sector: "Automobile and Auto Components" },
  { symbol: "ESCORTS", name: "Escorts Kubota", sector: "Automobile and Auto Components" },
  { symbol: "EXIDEIND", name: "Exide Industries", sector: "Automobile and Auto Components" },
  { symbol: "FEDERALBNK", name: "Federal Bank", sector: "Financial Services" },
  { symbol: "FORCEMOT", name: "Force Motors", sector: "Automobile and Auto Components" },
  { symbol: "FORTIS", name: "Fortis Healthcare", sector: "Healthcare" },
  { symbol: "GAIL", name: "GAIL", sector: "Oil, Gas & Consumable Fuels" },
  { symbol: "GLENMARK", name: "Glenmark", sector: "Healthcare" },
  { symbol: "GNFC", name: "Gujarat Narmada Valley Fertilizers", sector: "Chemicals" },
  { symbol: "GODFRYPHLP", name: "Godfrey Phillips", sector: "FMCG" },
  { symbol: "GODREJCP", name: "Godrej Consumer", sector: "FMCG" },
  { symbol: "GODREJPROP", name: "Godrej Properties", sector: "Realty" },
  { symbol: "GRANULES", name: "Granules India", sector: "Healthcare" },
  { symbol: "GRASIM", name: "Grasim", sector: "Construction Materials" },
  { symbol: "GUJGASLTD", name: "Gujarat Gas", sector: "Oil, Gas & Consumable Fuels" },
  { symbol: "HAL", name: "Hindustan Aeronautics", sector: "Capital Goods" },
  { symbol: "HAVELLS", name: "Havells", sector: "Consumer Durables" },
  { symbol: "HCLTECH", name: "HCL Technologies", sector: "Information Technology" },
  { symbol: "HDFCAMC", name: "HDFC AMC", sector: "Financial Services" },
  { symbol: "HDFCBANK", name: "HDFC Bank", sector: "Financial Services" },
  { symbol: "HDFCLIFE", name: "HDFC Life", sector: "Financial Services" },
  { symbol: "HEROMOTOCO", name: "Hero MotoCorp", sector: "Automobile and Auto Components" },
  { symbol: "HINDALCO", name: "Hindalco", sector: "Metals & Mining" },
  { symbol: "HINDPETRO", name: "HPCL", sector: "Oil, Gas & Consumable Fuels" },
  { symbol: "HINDZINC", name: "Hindustan Zinc", sector: "Metals & Mining" },
  { symbol: "HUDCO", name: "HUDCO", sector: "Financial Services" },
  { symbol: "HYUNDAI", name: "Hyundai Motor India", sector: "Automobile and Auto Components" },
  { symbol: "ICICIBANK", name: "ICICI Bank", sector: "Financial Services" },
  { symbol: "ICICIGI", name: "ICICI Lombard", sector: "Financial Services" },
  { symbol: "ICICIPRULI", name: "ICICI Prudential", sector: "Financial Services" },
  { symbol: "IDEA", name: "Vodafone Idea", sector: "Telecommunication" },
  { symbol: "IDFCFIRSTB", name: "IDFC First Bank", sector: "Financial Services" },
  { symbol: "IEX", name: "Indian Energy Exchange", sector: "Financial Services" },
  { symbol: "IGL", name: "Indraprastha Gas", sector: "Oil, Gas & Consumable Fuels" },
  { symbol: "INDHOTEL", name: "Indian Hotels", sector: "Consumer Services" },
  { symbol: "INDIAMART", name: "IndiaMART", sector: "Information Technology" },
  { symbol: "INDIGO", name: "InterGlobe Aviation", sector: "Services" },
  { symbol: "INDUSINDBK", name: "IndusInd Bank", sector: "Financial Services" },
  { symbol: "INDUSTOWER", name: "Indus Towers", sector: "Telecommunication" },
  { symbol: "INFY", name: "Infosys", sector: "Information Technology" },
  { symbol: "IOC", name: "Indian Oil", sector: "Oil, Gas & Consumable Fuels" },
  { symbol: "IRB", name: "IRB Infrastructure", sector: "Construction" },
  { symbol: "IRCTC", name: "IRCTC", sector: "Consumer Services" },
  { symbol: "IREDA", name: "IREDA", sector: "Financial Services" },
  { symbol: "IRFC", name: "IRFC", sector: "Financial Services" },
  { symbol: "ITC", name: "ITC", sector: "FMCG" },
  { symbol: "JINDALSTEL", name: "Jindal Steel", sector: "Metals & Mining" },
  { symbol: "JIOFIN", name: "Jio Financial Services", sector: "Financial Services" },
  { symbol: "JKCEMENT", name: "JK Cement", sector: "Construction Materials" },
  { symbol: "JSWENERGY", name: "JSW Energy", sector: "Power" },
  { symbol: "JSWSTEEL", name: "JSW Steel", sector: "Metals & Mining" },
  { symbol: "JUBLFOOD", name: "Jubilant FoodWorks", sector: "Consumer Services" },
  { symbol: "KALYANKJIL", name: "Kalyan Jewellers", sector: "Consumer Durables" },
  { symbol: "KOTAKBANK", name: "Kotak Mahindra Bank", sector: "Financial Services" },
  { symbol: "KPITTECH", name: "KPIT Technologies", sector: "Information Technology" },
  { symbol: "LALPATHLAB", name: "Dr Lal PathLabs", sector: "Healthcare" },
  { symbol: "LAURUSLABS", name: "Laurus Labs", sector: "Healthcare" },
  { symbol: "LICHSGFIN", name: "LIC Housing Finance", sector: "Financial Services" },
  { symbol: "LICI", name: "LIC", sector: "Financial Services" },
  { symbol: "LODHA", name: "Macrotech Developers", sector: "Realty" },
  { symbol: "LT", name: "Larsen & Toubro", sector: "Construction" },
  { symbol: "LTF", name: "L&T Finance", sector: "Financial Services" },
  { symbol: "LTIM", name: "LTIMindtree", sector: "Information Technology" },
  { symbol: "LTTS", name: "L&T Technology Services", sector: "Information Technology" },
  { symbol: "LUPIN", name: "Lupin", sector: "Healthcare" },
  { symbol: "M&M", name: "Mahindra & Mahindra", sector: "Automobile and Auto Components" },
  { symbol: "M&MFIN", name: "Mahindra Finance", sector: "Financial Services" },
  { symbol: "MANAPPURAM", name: "Manappuram Finance", sector: "Financial Services" },
  { symbol: "MARICO", name: "Marico", sector: "FMCG" },
  { symbol: "MARUTI", name: "Maruti Suzuki", sector: "Automobile and Auto Components" },
  { symbol: "MAXHEALTH", name: "Max Healthcare", sector: "Healthcare" },
  { symbol: "MAZDOCK", name: "Mazagon Dock", sector: "Capital Goods" },
  { symbol: "MCDOWELL-N", name: "United Spirits", sector: "FMCG" },
  { symbol: "MCX", name: "Multi Commodity Exchange", sector: "Financial Services" },
  { symbol: "METROPOLIS", name: "Metropolis", sector: "Healthcare" },
  { symbol: "MFSL", name: "Max Financial Services", sector: "Financial Services" },
  { symbol: "MGL", name: "Mahanagar Gas", sector: "Oil, Gas & Consumable Fuels" },
  { symbol: "MOTHERSON", name: "Samvardhana Motherson", sector: "Automobile and Auto Components" },
  { symbol: "MOTILALOFS", name: "Motilal Oswal Financial", sector: "Financial Services" },
  { symbol: "MPHASIS", name: "Mphasis", sector: "Information Technology" },
  { symbol: "MRF", name: "MRF", sector: "Automobile and Auto Components" },
  { symbol: "MUTHOOTFIN", name: "Muthoot Finance", sector: "Financial Services" },
  { symbol: "NAM-INDIA", name: "Nippon Life India AMC", sector: "Financial Services" },
  { symbol: "NATIONALUM", name: "National Aluminium", sector: "Metals & Mining" },
  { symbol: "NAUKRI", name: "Info Edge", sector: "Information Technology" },
  { symbol: "NHPC", name: "NHPC", sector: "Power" },
  { symbol: "NMDC", name: "NMDC", sector: "Metals & Mining" },
  { symbol: "NTPC", name: "NTPC", sector: "Power" },
  { symbol: "NUVAMA", name: "Nuvama Wealth Management", sector: "Financial Services" },
  { symbol: "NYKAA", name: "FSN E-Commerce", sector: "Consumer Services" },
  { symbol: "OBEROIRLTY", name: "Oberoi Realty", sector: "Realty" },
  { symbol: "OFSS", name: "Oracle Financial Services", sector: "Information Technology" },
  { symbol: "OIL", name: "Oil India", sector: "Oil, Gas & Consumable Fuels" },
  { symbol: "ONGC", name: "ONGC", sector: "Oil, Gas & Consumable Fuels" },
  { symbol: "PATANJALI", name: "Patanjali Foods", sector: "FMCG" },
  { symbol: "PAYTM", name: "One 97 Communications", sector: "Financial Services" },
  { symbol: "PEL", name: "Piramal Enterprises", sector: "Financial Services" },
  { symbol: "PERSISTENT", name: "Persistent Systems", sector: "Information Technology" },
  { symbol: "PETRONET", name: "Petronet LNG", sector: "Oil, Gas & Consumable Fuels" },
  { symbol: "PFC", name: "Power Finance", sector: "Financial Services" },
  { symbol: "PIDILITIND", name: "Pidilite", sector: "Chemicals" },
  { symbol: "PIIND", name: "PI Industries", sector: "Chemicals" },
  { symbol: "PNB", name: "Punjab National Bank", sector: "Financial Services" },
  { symbol: "POLYCAB", name: "Polycab", sector: "Capital Goods" },
  { symbol: "POWERGRID", name: "Power Grid", sector: "Power" },
  { symbol: "POWERINDIA", name: "Hitachi Energy India", sector: "Capital Goods" },
  { symbol: "PREMIERENE", name: "Premier Energies", sector: "Capital Goods" },
  { symbol: "PRESTIGE", name: "Prestige Estates", sector: "Realty" },
  { symbol: "RECLTD", name: "REC", sector: "Financial Services" },
  { symbol: "RELIANCE", name: "Reliance Industries", sector: "Oil, Gas & Consumable Fuels" },
  { symbol: "SAMMAANCAP", name: "Sammaan Capital", sector: "Financial Services" },
  { symbol: "SBICARD", name: "SBI Cards", sector: "Financial Services" },
  { symbol: "SBILIFE", name: "SBI Life", sector: "Financial Services" },
  { symbol: "SBIN", name: "State Bank of India", sector: "Financial Services" },
  { symbol: "SHREECEM", name: "Shree Cement", sector: "Construction Materials" },
  { symbol: "SHRIRAMFIN", name: "Shriram Finance", sector: "Financial Services" },
  { symbol: "SIEMENS", name: "Siemens", sector: "Capital Goods" },
  { symbol: "SJVN", name: "SJVN", sector: "Power" },
  { symbol: "SOLARINDS", name: "Solar Industries", sector: "Chemicals" },
  { symbol: "SONACOMS", name: "Sona BLW", sector: "Automobile and Auto Components" },
  { symbol: "SRF", name: "SRF", sector: "Chemicals" },
  { symbol: "SUNPHARMA", name: "Sun Pharma", sector: "Healthcare" },
  { symbol: "SUPREMEIND", name: "Supreme Industries", sector: "Capital Goods" },
  { symbol: "SWIGGY", name: "Swiggy", sector: "Consumer Services" },
  { symbol: "SYNGENE", name: "Syngene", sector: "Healthcare" },
  { symbol: "TATACHEM", name: "Tata Chemicals", sector: "Chemicals" },
  { symbol: "TATACOMM", name: "Tata Communications", sector: "Telecommunication" },
  { symbol: "TATACONSUM", name: "Tata Consumer", sector: "FMCG" },
  { symbol: "TATAELXSI", name: "Tata Elxsi", sector: "Information Technology" },
  { symbol: "TATAMOTORS", name: "Tata Motors", sector: "Automobile and Auto Components" },
  { symbol: "TATAPOWER", name: "Tata Power", sector: "Power" },
  { symbol: "TATASTEEL", name: "Tata Steel", sector: "Metals & Mining" },
  { symbol: "TCS", name: "Tata Consultancy Services", sector: "Information Technology" },
  { symbol: "TECHM", name: "Tech Mahindra", sector: "Information Technology" },
  { symbol: "TITAN", name: "Titan", sector: "Consumer Durables" },
  { symbol: "TORNTPHARM", name: "Torrent Pharma", sector: "Healthcare" },
  { symbol: "TORNTPOWER", name: "Torrent Power", sector: "Power" },
  { symbol: "TRENT", name: "Trent", sector: "Consumer Services" },
  { symbol: "TUBEINVEST", name: "Tube Investments of India", sector: "Automobile and Auto Components" },
  { symbol: "TVSMOTOR", name: "TVS Motor", sector: "Automobile and Auto Components" },
  { symbol: "UBL", name: "United Breweries", sector: "FMCG" },
  { symbol: "ULTRACEMCO", name: "UltraTech Cement", sector: "Construction Materials" },
  { symbol: "UNIONBANK", name: "Union Bank", sector: "Financial Services" },
  { symbol: "UPL", name: "UPL", sector: "Chemicals" },
  { symbol: "VBL", name: "Varun Beverages", sector: "FMCG" },
  { symbol: "VEDL", name: "Vedanta", sector: "Metals & Mining" },
  { symbol: "VMM", name: "Vishal Mega Mart", sector: "Consumer Services" },
  { symbol: "VOLTAS", name: "Voltas", sector: "Consumer Durables" },
  { symbol: "WAAREEENER", name: "Waaree Energies", sector: "Capital Goods" },
  { symbol: "WIPRO", name: "Wipro", sector: "Information Technology" },
  { symbol: "YESBANK", name: "Yes Bank", sector: "Financial Services" },
  { symbol: "ZOMATO", name: "Eternal (formerly Zomato)", sector: "Consumer Services" },
  { symbol: "ZYDUSLIFE", name: "Zydus Life", sector: "Healthcare" },
  { symbol: "360ONE", name: "360 ONE WAM", sector: "Financial Services" },
];

module.exports = FO_UNIVERSE;
